// This file was generated by RedwoodJS
import AboutPageType from '/Users/phuocdo/Workspace/redwoodjs/vida/web/src/pages/AboutPage/AboutPage'
import CreateDashboardPageType from '/Users/phuocdo/Workspace/redwoodjs/vida/web/src/pages/CreateDashboardPage/CreateDashboardPage'
import DashboardPageType from '/Users/phuocdo/Workspace/redwoodjs/vida/web/src/pages/DashboardPage/DashboardPage'
import DashboardsPageType from '/Users/phuocdo/Workspace/redwoodjs/vida/web/src/pages/DashboardsPage/DashboardsPage'
import EditDashboardPageType from '/Users/phuocdo/Workspace/redwoodjs/vida/web/src/pages/EditDashboardPage/EditDashboardPage'
import FatalErrorPageType from '/Users/phuocdo/Workspace/redwoodjs/vida/web/src/pages/FatalErrorPage/FatalErrorPage'
import HomePageType from '/Users/phuocdo/Workspace/redwoodjs/vida/web/src/pages/HomePage/HomePage'
import NewDashboardPageType from '/Users/phuocdo/Workspace/redwoodjs/vida/web/src/pages/NewDashboardPage/NewDashboardPage'
import NotFoundPageType from '/Users/phuocdo/Workspace/redwoodjs/vida/web/src/pages/NotFoundPage/NotFoundPage'
import StartPageType from '/Users/phuocdo/Workspace/redwoodjs/vida/web/src/pages/StartPage/StartPage'
import UserHomePageType from '/Users/phuocdo/Workspace/redwoodjs/vida/web/src/pages/UserHomePage/UserHomePage'

declare global {
  const AboutPage: typeof AboutPageType
  const CreateDashboardPage: typeof CreateDashboardPageType
  const DashboardPage: typeof DashboardPageType
  const DashboardsPage: typeof DashboardsPageType
  const EditDashboardPage: typeof EditDashboardPageType
  const FatalErrorPage: typeof FatalErrorPageType
  const HomePage: typeof HomePageType
  const NewDashboardPage: typeof NewDashboardPageType
  const NotFoundPage: typeof NotFoundPageType
  const StartPage: typeof StartPageType
  const UserHomePage: typeof UserHomePageType
}
